# The proper acceleration it experiences relative to free fall. As a consequence an accelerometer
# at rest relative to the Earth's surface will indicate approximately 1g (9.81m/s^2) upwards. To
# obtain the acceleration due to motion with respect to the earth, this gravity offset should be
# subtracted.

string name  # The name of the body containing the accelerometer
float32 x  # Acceleration along the x-axis in m/s2
float32 y  # Acceleration along the y-axis in m/s2
float32 z  # Acceleration along the z-axis in m/s2