# The beam effector allows a player to position itself on the field before the start of each half.
# The x and y coordinates define the position on the field with respect to the field's coordinate
# system, where (0,0) is the absolute center of the field. The rot specifies the facing angle of
# the player. Zero points to positive x-axis, 90 to positive y-axis.

float64 x  # metres
float64 y  # metres
float64 rot  # degrees