uint8 TYPE_CENTRE_CIRCLE=0
uint8 TYPE_CORNER=1
uint8 TYPE_T_JUNCTION=2

uint8 type
Spherical center  # The point at the center of the field feature
float32 orientation_w  # W-component of relative orientation quaternion of the field feature
float32 orientation_x  # X-component of relative orientation quaternion of the field feature
float32 orientation_y  # Y-component of relative orientation quaternion of the field feature
float32 orientation_z  # Z-component of relative orientation quaternion of the field feature
