# Information about the angle of the correponding single-axis hinge joint. A zero angle
# corresponds to straightly aligned bodies. The position angle of each hinge joint
# perceptor is sent every cycle.
#
# Each hinge joint has minimum and maximum limits on its angular position. This varies
# from hinge to hinge and depends upon the model being used.

string name  # The name of the corresponding hinge joint
float32 ax  # The current position angle in degrees