# The say effector permits communication among agents by broadcasting messages. In order to say 
# something, the following command has to be employed.
#
# See restrictions: https://gitlab.com/robocup-sim/SimSpark/-/wikis/Perceptors#restrictions

string message  # Up to 20 characters, which may be taken from the ASCII printing character subset
                # [0x20, 0x7E] except the white space character and the normal brackets ( and )